### ISSUE TITLE
[BUG] Charsets with one or two characters immediately cause a crash

### ISSUE THREAD

**Issue by AverseABFun** [quackduck/aces#5]
I propose that instead it just shows a fatal error instead of ![image](https://github.com/quackduck/aces/assets/81586710/e373efbd-6b55-4019-99be-30657a57c481)

**Comment by quackduck** [comment]
<img width="586" alt="image" src="https://github.com/quackduck/aces/assets/38882631/5ed2fefa-d1f9-43dc-8eeb-58487b908cd3">
are you using the latest code?

**Comment by AverseABFun** [comment]
oh nope whoops
